services:
  - type: web
    name: weather-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn weather_app:app"
    envVars:
      - key: WEATHER_API_KEY
        sync: false
        
